export const roleDistribution = {
    5:  {townsfolk: 3, outsider: 0, minion: 1},
    6:  {townsfolk: 3, outsider: 1, minion: 1},
    7:  {townsfolk: 5, outsider: 0, minion: 1},
    8:  {townsfolk: 5, outsider: 1, minion: 1},
    9:  {townsfolk: 5, outsider: 2, minion: 1},
    10: {townsfolk: 7, outsider: 0, minion: 2},
    11: {townsfolk: 7, outsider: 1, minion: 2},
    12: {townsfolk: 7, outsider: 2, minion: 2},
    13: {townsfolk: 9, outsider: 0, minion: 3},
    14: {townsfolk: 9, outsider: 1, minion: 3},
    15: {townsfolk: 9, outsider: 2, minion: 3},
}

export const roles = {
    chef: 'townsfolk',
    empath: 'townsfolk',
    fortuneTeller: 'townsfolk',
    investigator: 'townsfolk',
    librarian: 'townsfolk',
    monk: 'townsfolk',
    mayor: 'townsfolk',
    ravenkeeper: 'townsfolk',
    slayer: 'townsfolk',
    soldier: 'townsfolk',
    undertaker: 'townsfolk',
    virgin: 'townsfolk',
    butler: 'outsider',
    drunk: 'outsider',
    saint: 'outsider',
    recluse: 'outsider',
    spy: 'minion',
    scarletWoman: 'minion',
    poisoner: 'minion',
    baron: 'minion',
    imp: 'imp',
}